import json
import requests
from ddgs import DDGS
def web_search(query: str, max_results: int = 5) -> str:
    """Searches DuckDuckGo and returns text results joined together."""
    try:
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=5, region="us-en"))
            if not results:
                return "No search results found."

            formatted_results = []
            for i, res in enumerate(results, 1):
                formatted_results.append(
                    f"Result {i}:\nTitle: {res.get('title')}\nURL: {res.get('href')}\nSnippet: {res.get('body')}\n"
                )
            return "\n---\n".join(formatted_results)
    except Exception as e:
        return f"Error executing search: {str(e)}"


# --- Schema Definitions ---
# The schema your LLM uses to understand how to call your custom tool
tool_definitions = [
    {
        "type": "function",
        "function": {
            "name": "web_search",
            "description": "Search the web using DuckDuckGo to verify citation details, titles, authors, DOIs, or publishers.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query (e.g., article title, specific DOI, or author name)."
                    }
                },
                "required": ["query"]
            }
        }
    }
]

# Your expected structured JSON output format
response_schema = {}


# --- Main Accessor Function ---
def openrouter_accessor(header: str, citation: str or dict, model: str):
    api_key = ""
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    # Extract clean citation text string
    citation_str = citation if isinstance(citation, str) else next(iter(citation.values()), "")

    # Build initial message history
    messages = [
        {
            "role": "user",
            "content": (
                f"{header} \n\n {citation_str}"
            )
        }
    ]

    # --- STEP 1: Ask the LLM if it needs to make a search call ---
    payload = {
        "model": model,
        "messages": messages,
        "tools": tool_definitions,
        "tool_choice": "required"  # This section you can edit whether the LLM needs to make a internet search
    }

    response = requests.post(url, headers=headers, json=payload)
    response.raise_for_status()
    response_json = response.json()

    choice = response_json["choices"][0]
    message = choice["message"]

    # --- STEP 2: Handle Tool Execution (If LLM decides to search) ---
    if message.get("tool_calls"):
        # Append the assistant's thought process/tool call intent to the history
        messages.append(message)

        for tool_call in message["tool_calls"]:
            if tool_call["function"]["name"] == "web_search":
                # Extract the query generated by the LLM
                arguments = json.loads(tool_call["function"]["arguments"])
                query = arguments.get("query")

                print(f"[Tool Call] Searching web for: '{query}'")
                search_result = web_search(query)

                # Append the search results back to the message history
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call["id"],
                    "name": "web_search",
                    "content": search_result
                })

        # --- STEP 3: Second call to get the final answer with STRICT Structured Output ---
        final_payload = {
            "model": model,
            "messages": messages,
            "response_format": response_schema  # Now we can safely apply structured output
        }

        final_response = requests.post(url, headers=headers, json=final_payload)
        final_response.raise_for_status()
        final_json = final_response.json()

        return json.loads(final_json["choices"][0]["message"]["content"])

    else:
        # If the model surprisingly answered directly without using the tool,
        # it won't be formatted. We make a quick follow-up to enforce the structure.
        messages.append(message)
        messages.append(
            {"role": "user", "content": "Please output your final evaluation using the requested schema structure."})

        final_payload = {
            "model": model,
            "messages": messages,
            "response_format": response_schema
        }
        final_response = requests.post(url, headers=headers, json=final_payload)
        return json.loads(final_response.json()["choices"][0]["message"]["content"])

if __name__ == "__main__":
    header = "Analyze this citation and tell me whether its real or not. Please use the various ways to categorize the different components of the citation."
    citation = "\n Here is the reference:\n Kearney PM, McCarthy M, Rengarajan S, O'Keeffe LM, Avery K, Chan AW, Devane D, Davies G, Gale C, Hemkens LG, Juszczak E, Kwakkenbos L, Langan SM, Lugg-Widger F, Moher D, Schmidt M, Thabane L, Thombs BD, Toader AM, Watkins A, Farrin AJ, Zwarenstein M, Sydes MR, Williamson PR, Markham S. Reporting of Cohort and Routinely Collected Data in Randomised Controlled Trial Protocols (SPIRIT-ROUTINE): extension checklist with explanation and elaboration. BMJ. 2026;393:. doi:10.1136/bmj-2025-087095"

    print(openrouter_accessor(header ,citation, "openai/gpt-oss-20b:free"))